name: Build (ESP32)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sample repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install west and deps
        run: |
          pip install west

      - name: Set up Zephyr workspace
        run: |
          west init zephyrproject
          cd zephyrproject
          west update
          west zephyr-export

      - name: Install Zephyr build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build gperf cmake ccache dfu-util \
            device-tree-compiler wget python3-pip python3-setuptools \
            python3-wheel xz-utils file make gcc git unzip

      - name: Build sample
        run: |
          cd zephyrproject
          west build -b m5stack_atom_lite/esp32/procpu ../zephyr-atom-wifi-sample \
            -- -DBOARD_ROOT=../zephyr-atom-wifi-sample \
               -DCONFIG_ESP32_USE_UNSUPPORTED_REVISION=y
