name: Build Zephyr App

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install west and dependencies
        run: |
          pip install west
          cd $GITHUB_WORKSPACE
          west init -l mqtt_subscriber
          west update
          west zephyr-export
          pip install -r zephyr/scripts/requirements.txt

      - name: Build the app
        run: |
          cd $GITHUB_WORKSPACE
          west build -b m5stack_atom_lite/esp32/procpu mqtt_subscriber \
            -- -DBOARD_ROOT=$GITHUB_WORKSPACE/mqtt_subscriber \
               -DCONFIG_ESP32_USE_UNSUPPORTED_REVISION=y
