name: Build Zephyr App

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install west and requirements
        run: |
          pip install west
          west init -m https://github.com/zephyrproject-rtos/zephyr --mr main zephyr
          west update
          west zephyr-export
          pip install -r zephyr/scripts/requirements.txt

      - name: Build project
        run: |
          west build -b m5stack_atom_lite/esp32/procpu . \
            -- -DBOARD_ROOT=${PWD} \
               -DCONFIG_ESP32_USE_UNSUPPORTED_REVISION=y
