name: Build Zephyr App

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Prepare project structure
        run: |
          cd $GITHUB_WORKSPACE
          git clone --depth=1 https://github.com/zephyrproject-rtos/zephyr.git
          pip install west
          west init -l zephyr
          west update
          west zephyr-export
          source zephyr/zephyr-env.sh
          pip install -r zephyr/scripts/requirements.txt

      - name: Build mqtt_subscriber
        run: |
          cd $GITHUB_WORKSPACE
          west build -b m5stack_atom_lite/esp32/procpu . \
            -- -DCONFIG_ESP32_USE_UNSUPPORTED_REVISION=y
