name: Build Zephyr App

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Setup ESP32 toolchain
        run: |
          mkdir -p ~/esp
          cd ~/esp
          wget https://dl.espressif.com/dl/xtensa-esp32-elf-gcc8_4_0-esp-2021r2-patch5-linux-amd64.tar.gz
          tar -xzf xtensa-esp32-elf-gcc8_4_0-esp-2021r2-patch5-linux-amd64.tar.gz
          echo "ZEPHYR_TOOLCHAIN_VARIANT=espressif" >> $GITHUB_ENV
          echo "ESPRESSIF_TOOLCHAIN_PATH=$HOME/esp/xtensa-esp32-elf" >> $GITHUB_ENV

      - name: Prepare project structure
        run: |
          cd $GITHUB_WORKSPACE
          git clone --depth=1 https://github.com/zephyrproject-rtos/zephyr.git
          pip install west requests
          cd zephyr
          west init -l .
          west update
          west zephyr-export
          west blobs fetch hal_espressif
          pip install -r scripts/requirements.txt

      - name: Build project
        run: |
          cd $GITHUB_WORKSPACE
          west build -b m5stack_atom_lite/esp32/procpu . \
            -- -DCONFIG_ESP32_USE_UNSUPPORTED_REVISION=y
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: zephyr-artifacts
          path: |
            build/zephyr/zephyr.elf
            build/zephyr/zephyr.bin
            build/zephyr/bootloader/bootloader.bin

      - name: Add CI badge to README (optional manual step)
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          echo "![CI](https://github.com/${{ github.repository }}/actions/workflows/ci.yml/badge.svg)" >> README.md
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add README.md
          git commit -m "Add CI status badge"
          git push || echo "Badge already exists or push skipped"
