name: Build Zephyr App

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Prepare project structure
        run: |
          pip install west
          mkdir -p ~/projects
          rsync -av --exclude='.git' ./ ~/projects/mqtt_subscriber
          mv .git ~/projects/
          cd ~/projects
          west init -l mqtt_subscriber
          west update
          west zephyr-export
          pip install -r zephyr/scripts/requirements.txt

      - name: Build mqtt_subscriber
        run: |
          cd ~/projects/mqtt_subscriber
          west build -b m5stack_atom_lite/esp32/procpu . \
            -- -DCONFIG_ESP32_USE_UNSUPPORTED_REVISION=y
